/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/dLNOiPSZlZp
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardContent, Card } from "@/components/ui/card";
import { getWeather } from "@/app/weather.action";

export async function WeatherCard({
  city,
  unit,
}: {
  city: string;
  unit: string;
}) {
  const data = await getWeather();

  return (
    <Card className="w-full max-w-sm mt-4">
      <CardContent className="p-6 flex flex-col items-center gap-4 rounded-md bg-blue-400">
        <div className="flex items-center gap-4">
          <div className="text-6xl font-bold">
            {data.temperature} {data.unit}
          </div>
          <SunIcon className="w-12 h-12" />
        </div>
        <div className="text-white font-bold">{data.description}</div>
      </CardContent>
    </Card>
  );
}

function SunIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="m17.66 17.66 1.41 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  );
}
